### ISSUE TITLE
Improve the game

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m2-evaluacion-intermedia-AntonellaM#1]
Awesome work @AntonellaM  !!!

Here you have some tips to improve it:

- [x] Don't use an object to resolve the counter, a good old constant will suffice ;)
- [ ] No need to use a template literal for a single constant.
- [x] Move variables and constants declarations to the top of the file
- [x] Since you are writing so many times 'clueEl.innerHTML = "something", what about making a function that accepts a string as param a writes it inside 'clueEl'?
- [x] Remove comments!
- [x] Try to use imperative for your commit messages. Ex. - > Fix central text
- [x] Define a good structure of folders and files for the project

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

Let me know if you have any doubts ;)

Go for it!!

**Comment by AntonellaM** [comment]
@nasivuela I think every basic thing is done, when my imagination starts to work... I'll try to improve it further! :)

**Comment by nasivuela** [comment]
Cool @AntonellaM !!!

I' closing this, but here you have some final clues.

- I have unchecked one point, it is related to this line `contEl.innerHTML = `${counter}`;` which will be better as `contEl.innerHTML = counter;`
- Since you have some simple functions with only one line, what about making them arrow functions to practice? And later you can remove the block and the return keyword and convert them to one-line arrow functions ;)

Good work!

![](https://media.giphy.com/media/5ZQCTwHXBO2Aw/giphy.gif)
